Discussion/LaZuittEcommerce/LaZuittEcommerce/Controllers/CourseController.cs
using LaZuittEcommerce.Data;
using Microsoft.AspNetCore.Mvc;

namespace LaZuittEcommerce.Controllers;

public class CourseController : Controller
{
    private readonly LaZuittContext _context;

    public CourseController(LaZuittContext context)
    {
        _context = context;
    }

    public IActionResult Index()
    {
        return View(_context.Course.ToList());
    }
}

Discussion/LaZuittEcommerce/LaZuittEcommerce/Controllers/HistoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using LaZuittEcommerce.Data;
using LaZuittEcommerce.Models;
using Microsoft.AspNetCore.Mvc;

namespace LaZuittEcommerce.Controllers;

public class HistoryController : Controller
{
    private readonly LaZuittContext _context;

    public HistoryController(LaZuittContext context)
    {
        _context = context;
    }

    public IActionResult Index()
    {
        List<OrderHistory> historyModel = new List<OrderHistory>();

        var orderHistory = (from ec in _context.EnrollCourses

                            join c in _context.Course on ec.CourseId equals c.Id
                            join s in _context.Student on ec.EnrollId equals s.Id
                            join e in _context.Enroll on ec.EnrollId equals e.Id

                            select new
                            {
                                Id = ec.EnrollId,
                                FullName = s.FirstName + " " + s.LastName,
                                Billing = s.BillingAddress,
                                DateEnrolled = e.EnrollDate,
                                Title = c.Title,
                                Description = c.Description,
                                Price = c.Price,
                                Quantity = c.Quantity
                            }).ToList();

        foreach (var item in orderHistory)

            historyModel.Add(new OrderHistory()
            {
                Id = item.Id,
                FullName = item.FullName,
                Billing = item.Billing,
                DateEnrolled = item.DateEnrolled,
                Title = item.Title,
                Description = item.Description,
                Price = item.Price,
                Quantity = item.Quantity
            });

        return View(historyModel);
    }
}

Discussion/LaZuittEcommerce/LaZuittEcommerce/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LaZuitt Ecommerce</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/LaZuittEcommerce.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Course" asp-action="Index">Course</a>
                <a class="navbar-brand mr-auto" asp-area="" asp-controller="History" asp-action="Index">History</a>
                @if (Convert.ToInt32(TempData["Count"]) > 0)
                {
                    <a class="navbar-brand text-dange" asp-area="" asp-controller="Cart" asp-action="Index">Cart (@TempData["Count"])</a>
                    TempData.Keep();
                }
                else
                {
                    <a class="navbar-brand " asp-area="" asp-controller="Cart" asp-action="Index">Cart</a>
                }
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_MessagePartial" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - LaZuitt Ecommerce
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Discussion/LaZuittEcommerce/LaZuittEcommerce/Views/Shared/_MessagePartial.cshtml
@if (TempData["Message"] != null)
{
    <script>
        alert('@Html.Raw(TempData["Message"])')
    </script>
}